subtitle: "教材补充解释与说明"
title-slide-attributes:
    data-background-image: https://objectstorage.ap-singapore-1.oraclecloud.com/n/axwslyfy9krb/b/qf/o/work%2Fschool-gongji.jpg
    data-background-size: contain
    data-background-opacity: "0.5"
author: "邱飞"

format:
  revealjs:
    slide-level: 3
    slide-number: true
    show-slide-number: all
    fig-align: center
    #smaller: true
    theme: sky
    logo: https://objectstorage.ap-singapore-1.oraclecloud.com/n/axwslyfy9krb/b/qf/o/work%2Fzwu_logo.png
    embed-resources: true
    footer: "hfutqiufei@163.com"
    scrollable: true
    css: my.css


execute: 
  eval: true
  echo: true 